import { test } from 'node:test';
import assert from 'node:assert/strict';
import { simulateSlowLink, QUEUE_LIMIT_BYTES } from './index.mjs';
import { validateEvent, rng } from '../../../contracts/load/harness.mjs';

const mk = (linkBytesPerS) => ({
  name: 'slow', kind: 'slow_link', clients: 30, durationS: 20, linkBytesPerS,
  path: [{ t: 0, e: 0, n: 0, u: 100 }, { t: 20, e: 30, n: 0, u: 100 }],
});
const median = (a) => { const s = [...a].sort((x, y) => x - y); return s[s.length >> 1]; };
const lat = (r) => r.events.filter((e) => e.kind === 'bytes').map((e) => e.latencyMs);

test('slow link: queue bounded, delivery capped by link rate', () => {
  const sc = mk(50000);
  const r = simulateSlowLink(sc, { seed: 7 });
  assert.ok(r.maxQueueBytes <= QUEUE_LIMIT_BYTES);
  assert.ok(r.maxQueueBytes > 0);
  const total = new Array(30).fill(0);
  for (const e of r.events) {
    assert.deepEqual(validateEvent(e, 30), []);
    if (e.kind === 'bytes') total[e.id] += e.bytes;
  }
  for (let id = 0; id < 30; id++) assert.ok(total[id] <= 50000 * sc.durationS, `client ${id}`);
  assert.ok(total.some((b) => b > 0));
});

test('events sorted, connect/first_frame/close present per client', () => {
  const r = simulateSlowLink(mk(50000), { seed: 3 });
  for (let i = 1; i < r.events.length; i++) {
    const a = r.events[i - 1]; const b = r.events[i];
    assert.ok(a.tMs < b.tMs || (a.tMs === b.tMs && a.id <= b.id));
  }
  for (let id = 0; id < 30; id++) {
    const mine = r.events.filter((e) => e.id === id);
    assert.equal(mine[0].kind, 'connect');
    assert.equal(mine.at(-1).kind, 'close');
    assert.equal(mine.at(-1).tMs, 20000);
    const ff = mine.findIndex((e) => e.kind === 'first_frame');
    assert.ok(ff > 1 && mine[ff - 1].kind === 'level' && mine[ff - 1].level === 0 && mine[ff - 1].tMs === mine[ff].tMs);
    assert.ok(mine[ff - 2].kind === 'bytes' && mine[ff - 2].tMs === mine[ff].tMs);
  }
});

test('slow link latencies exceed fast link latencies', () => {
  const slow = median(lat(simulateSlowLink(mk(50000), { seed: 5 })));
  const fast = median(lat(simulateSlowLink(mk(5000000), { seed: 5 })));
  assert.ok(slow > fast, `${slow} > ${fast}`);
});

test('deterministic per seed, different across seeds', () => {
  const a = simulateSlowLink(mk(50000), { seed: 11 });
  assert.deepEqual(simulateSlowLink(mk(50000), { seed: 11 }), a);
  assert.notDeepEqual(simulateSlowLink(mk(50000), { seed: 12 }).events, a.events);
});

const mk2 = (clients, durationS, linkBytesPerS) => ({
  name: 'slow', kind: 'slow_link', clients, durationS, linkBytesPerS,
  path: [{ t: 0, e: 0, n: 0, u: 100 }, { t: durationS, e: 30, n: 0, u: 100 }],
});

// Independent replay of the generated byte total: per client, redraw wanted times and sizes, model the FIFO link
// and the queue limit, and sum the size of every payload offered before close (delivered, still queued or dropped).
function replayGeneratedBytes(clients, durationS, linkBytesPerS, seed) {
  const closeMs = durationS * 1000;
  let total = 0;
  for (let id = 0; id < clients; id++) {
    const rand = rng((seed + Math.imul(id + 1, 0x9e3779b1)) >>> 0);
    const inflight = []; // [size, doneMs], oldest first
    let want = 100 + rand() * 200;
    let free = 0;
    while (want < closeMs) {
      const size = 4096 + Math.floor(rand() * (40960 - 4096 + 1));
      const gap = 100 + rand() * 200;
      total += size;
      let t = want;
      const queued = () => inflight.reduce((a, x) => a + x[0], 0);
      const reap = () => { while (inflight.length && inflight[0][1] <= t) inflight.shift(); };
      reap();
      while (queued() + size > 262144 && inflight.length) t = Math.max(t, inflight.shift()[1]);
      reap();
      if (t >= closeMs) break;
      free = Math.max(t, free) + size / (linkBytesPerS / 1000);
      inflight.push([size, free]);
      want = t + gap;
    }
  }
  return total;
}

test('30 clients, 60 s, seed 1, 50000 B/s: conservation, undelivered and dropped pinned', () => {
  const r = simulateSlowLink(mk2(30, 60, 50000), { seed: 1 });
  const bytesEvents = r.events.filter((e) => e.kind === 'bytes');
  const delivered = bytesEvents.reduce((a, e) => a + e.bytes, 0);
  assert.equal(bytesEvents.length, 3932);
  assert.equal(delivered, 89265994);
  assert.equal(r.undeliveredBytes, 7325738);
  assert.equal(r.dropped, 504828);
  // Independent replay of each client's payload size sequence: delivered payloads are a FIFO prefix of it.
  for (let id = 0; id < 30; id++) {
    const rand = rng((1 + Math.imul(id + 1, 0x9e3779b1)) >>> 0);
    rand(); // first wanted time
    const mine = bytesEvents.filter((e) => e.id === id);
    for (const e of mine) {
      const size = 4096 + Math.floor(rand() * (40960 - 4096 + 1));
      rand(); // gap draw
      assert.equal(e.bytes, size, `client ${id} payload order`);
    }
  }
  // Generated total, recounted independently: replay each client's draws and queue, count every payload offered.
  const generated = replayGeneratedBytes(30, 60, 50000, 1);
  assert.equal(delivered + r.undeliveredBytes + r.dropped, generated);
  assert.ok(generated > delivered);
  assert.equal(r.maxQueueBytes, 262143);
});

test('latency is measured from wanted time, including backpressure wait (pinned)', () => {
  const r = simulateSlowLink(mk2(30, 60, 50000), { seed: 1 });
  const lats = r.events.filter((e) => e.kind === 'bytes').map((e) => e.latencyMs);
  assert.ok(Math.abs(Math.max(...lats) - 5884.9577936409405) < 1e-6);
  assert.ok(Math.abs(lats.reduce((a, b) => a + b, 0) - 18696370.16254823) < 1e-3);
  // FIFO link: consecutive deliveries of one client are at least one payload's transit time apart.
  const prev = new Map();
  for (const e of r.events) {
    if (e.kind !== 'bytes') continue;
    if (prev.has(e.id)) assert.ok(e.tMs - prev.get(e.id) >= e.bytes / 50 - 1e-6, `client ${e.id} link spacing`);
    prev.set(e.id, e.tMs);
  }
});

test('no client receives a byte: no throw, log intact, no first_frame', () => {
  const r = simulateSlowLink(mk2(2, 10, 1000), { seed: 1 });
  assert.equal(r.events.length, 4);
  assert.deepEqual(r.events.map((e) => e.kind), ['connect', 'connect', 'close', 'close']);
  assert.equal(r.events.filter((e) => e.kind === 'first_frame').length, 0);
  assert.equal(r.undeliveredBytes, 508898);
  assert.equal(r.dropped, 59240);
});

test('rejects non slow_link scenario', () => {
  const sc = { ...mk(1000) };
  assert.throws(() => simulateSlowLink({ ...sc, kind: 'steady', linkBytesPerS: undefined }, { seed: 1 }));
});

const BAD_SEEDS = [['2^32', 2 ** 32], ['-1', -1], ['1.5', 1.5], ['NaN', NaN], ['undefined', undefined]];
for (const [name, seed] of BAD_SEEDS) {
  test(`rejects bad seed ${name}`, () => {
    assert.throws(() => simulateSlowLink(mk(50000), { seed }), /seed must be an integer in 0\.\.2\^32-1/);
  });
}

test('boundary seeds 0 and 2^32-1 are valid and give different logs', () => {
  const a = simulateSlowLink(mk(50000), { seed: 0 });
  const b = simulateSlowLink(mk(50000), { seed: 0xffffffff });
  assert.ok(a.events.length > 60 && b.events.length > 60);
  assert.notDeepEqual(a.events, b.events);
});
